services:
  - type: web
    name: health_web
    env: python
    buildCommand: pip install -r requirements.txt gunicorn
    startCommand: gunicorn main:app
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
    region: oregon
