services:
  - type: web
    name: health_web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SESSION_SECRET
        value: your_session_secret_here
        sync: false
      - key: DATABASE_URL
        value: your_database_url_here
        sync: false
    plan: free
    region: oregon
